---
default:
  image:
    name: gcr.io/kaniko-project/executor:debug-v0.10.0
    entrypoint: [""]

stages:
  - build

build-release:
  stage: build
  variables:
    CI_PROJECT_DIR: /go/app
  before_script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - >
      /kaniko/executor \
        --verbosity error \
        --context ${CI_PROJECT_DIR} \
        --destination ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA} \
        --destination ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG} \
        --destination eu.gcr.io/malt-build/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG} \
        --destination eu.gcr.io/malt-build/${CI_PROJECT_NAME}:${CI_COMMIT_SHORT_SHA}
  after_script:
    - shred -u /kaniko/.docker/config.json
  only:
    refs:
      - master
  tags:
    - kubernetes

build-only:
  stage: build
  variables:
    CI_PROJECT_DIR: /go/app
  script:
    - >
      /kaniko/executor \
        --verbosity error \
        --context ${CI_PROJECT_DIR} \
        --no-push
  except:
    refs:
      - master
  tags:
    - kubernetes
